/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as FinanceSlugRouteImport } from './routes/finance.$slug'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as SettlementsIndexRouteImport } from './routes/settlements.index'
import { Route as SettlementsSlugRouteImport } from './routes/settlements.$slug'
import { Route as TendersIndexRouteImport } from './routes/tenders.index'
import { Route as TendersSlugRouteImport } from './routes/tenders.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceSlugRoute = FinanceSlugRouteImport.update({
  id: '/finance/$slug',
  path: '/finance/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettlementsIndexRoute = SettlementsIndexRouteImport.update({
  id: '/settlements/',
  path: '/settlements/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettlementsSlugRoute = SettlementsSlugRouteImport.update({
  id: '/settlements/$slug',
  path: '/settlements/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersIndexRoute = TendersIndexRouteImport.update({
  id: '/tenders/',
  path: '/tenders/',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersSlugRoute = TendersSlugRouteImport.update({
  id: '/tenders/$slug',
  path: '/tenders/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/watchlist': typeof WatchlistRoute
  '/finance/$slug': typeof FinanceSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/settlements/$slug': typeof SettlementsSlugRoute
  '/tenders/$slug': typeof TendersSlugRoute
  '/finance/': typeof FinanceIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/settlements/': typeof SettlementsIndexRoute
  '/tenders/': typeof TendersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/watchlist': typeof WatchlistRoute
  '/finance/$slug': typeof FinanceSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/settlements/$slug': typeof SettlementsSlugRoute
  '/tenders/$slug': typeof TendersSlugRoute
  '/finance': typeof FinanceIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/settlements': typeof SettlementsIndexRoute
  '/tenders': typeof TendersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/watchlist': typeof WatchlistRoute
  '/finance/$slug': typeof FinanceSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/settlements/$slug': typeof SettlementsSlugRoute
  '/tenders/$slug': typeof TendersSlugRoute
  '/finance/': typeof FinanceIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/settlements/': typeof SettlementsIndexRoute
  '/tenders/': typeof TendersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/watchlist'
    | '/finance/$slug'
    | '/jobs/$slug'
    | '/settlements/$slug'
    | '/tenders/$slug'
    | '/finance/'
    | '/jobs/'
    | '/settlements/'
    | '/tenders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/watchlist'
    | '/finance/$slug'
    | '/jobs/$slug'
    | '/settlements/$slug'
    | '/tenders/$slug'
    | '/finance'
    | '/jobs'
    | '/settlements'
    | '/tenders'
  id:
    | '__root__'
    | '/'
    | '/watchlist'
    | '/finance/$slug'
    | '/jobs/$slug'
    | '/settlements/$slug'
    | '/tenders/$slug'
    | '/finance/'
    | '/jobs/'
    | '/settlements/'
    | '/tenders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WatchlistRoute: typeof WatchlistRoute
  FinanceSlugRoute: typeof FinanceSlugRoute
  JobsSlugRoute: typeof JobsSlugRoute
  SettlementsSlugRoute: typeof SettlementsSlugRoute
  TendersSlugRoute: typeof TendersSlugRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  SettlementsIndexRoute: typeof SettlementsIndexRoute
  TendersIndexRoute: typeof TendersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/$slug': {
      id: '/finance/$slug'
      path: '/finance/$slug'
      fullPath: '/finance/$slug'
      preLoaderRoute: typeof FinanceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settlements/': {
      id: '/settlements/'
      path: '/settlements'
      fullPath: '/settlements/'
      preLoaderRoute: typeof SettlementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settlements/$slug': {
      id: '/settlements/$slug'
      path: '/settlements/$slug'
      fullPath: '/settlements/$slug'
      preLoaderRoute: typeof SettlementsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders/': {
      id: '/tenders/'
      path: '/tenders'
      fullPath: '/tenders/'
      preLoaderRoute: typeof TendersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders/$slug': {
      id: '/tenders/$slug'
      path: '/tenders/$slug'
      fullPath: '/tenders/$slug'
      preLoaderRoute: typeof TendersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WatchlistRoute: WatchlistRoute,
  FinanceSlugRoute: FinanceSlugRoute,
  JobsSlugRoute: JobsSlugRoute,
  SettlementsSlugRoute: SettlementsSlugRoute,
  TendersSlugRoute: TendersSlugRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  SettlementsIndexRoute: SettlementsIndexRoute,
  TendersIndexRoute: TendersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
